---
all:
  children:
    proxmox:
      hosts:
        pve01.example.invalid:
          ansible_host: 192.168.130.10
          proxmox_allow_mgmt_iface_change: true
          proxmox_mgmt_iface: eno1
          proxmox_mgmt_address_cidr: 192.168.130.10/24
          proxmox_mgmt_gateway: 192.168.130.1
          proxmox_bridge_iface: eno2
          proxmox_bridge_address_cidr: ""
          proxmox_bridge_gateway: ""
