---
all:
  children:
    proxmox:
      hosts:
        weir:
          ansible_host: 192.168.128.103
          proxmox_allow_mgmt_iface_change: true
          proxmox_mgmt_iface: eno4
          proxmox_mgmt_address_cidr: 192.168.128.103/24
          proxmox_mgmt_gateway: 192.168.128.254
          proxmox_bridge_iface: ens2f0
          proxmox_bridge_address_cidr: ""
          proxmox_bridge_gateway: ""
